import { existsSync, readFileSync } from 'node:fs';
import { describe, expect, it, vi } from 'vitest';
import { loadConfig } from './config.js';

vi.mock('node:fs', () => ({
  existsSync: vi.fn(() => true),
  readFileSync: vi.fn(),
}));

describe('loadConfig', () => {
  it('should parse unquoted glob values', () => {
    vi.mocked(readFileSync).mockReturnValue(
      `dir: _treck
scope:
  include:
    - src/**/*.ts
    - src/**/*.tsx
  exclude:
    - **/*.test.*
    - **/*.spec.*`,
    );

    const config = loadConfig('/project');

    expect(config).toEqual({
      outputDir: '_treck',
      scope: {
        include: ['src/**/*.ts', 'src/**/*.tsx'],
        exclude: ['**/*.test.*', '**/*.spec.*'],
      },
    });
  });

  it('should strip double quotes from values', () => {
    vi.mocked(readFileSync).mockReturnValue(
      `dir: _treck
scope:
  include:
    - "src/**/*.ts"
  exclude:
    - "**/*.test.*"`,
    );

    const config = loadConfig('/project');

    expect(config?.scope.include).toEqual(['src/**/*.ts']);
    expect(config?.scope.exclude).toEqual(['**/*.test.*']);
  });

  it('should strip single quotes from values', () => {
    vi.mocked(readFileSync).mockReturnValue(
      `dir: _treck
scope:
  include:
    - 'src/**/*.ts'
  exclude:
    - '**/*.test.*'`,
    );

    const config = loadConfig('/project');

    expect(config?.scope.include).toEqual(['src/**/*.ts']);
    expect(config?.scope.exclude).toEqual(['**/*.test.*']);
  });

  it('should strip quotes from dir value', () => {
    vi.mocked(readFileSync).mockReturnValue(
      `dir: "docs"
scope:
  include:
    - src/**/*.ts`,
    );

    const config = loadConfig('/project');

    expect(config?.outputDir).toBe('docs');
  });

  it('should return null when config file does not exist', () => {
    vi.mocked(existsSync).mockReturnValueOnce(false);

    expect(loadConfig('/project')).toBeNull();
  });

  it('should skip comment lines between list items', () => {
    vi.mocked(readFileSync).mockReturnValue(
      `dir: _treck
scope:
  include:
    - src/**/*.ts
    # - old/pattern/**
    - lib/**/*.ts
  exclude:
    - **/*.test.*`,
    );

    const config = loadConfig('/project');

    expect(config?.scope.include).toEqual(['src/**/*.ts', 'lib/**/*.ts']);
  });

  it('should strip inline comments from list values', () => {
    vi.mocked(readFileSync).mockReturnValue(
      `dir: _treck
scope:
  include:
    - src/**/*.ts # TypeScript files
  exclude:
    - **/*.test.*`,
    );

    const config = loadConfig('/project');

    expect(config?.scope.include).toEqual(['src/**/*.ts']);
  });

  it('should handle key line with trailing comment', () => {
    vi.mocked(readFileSync).mockReturnValue(
      `dir: _treck
scope:
  include: # my patterns
    - src/**/*.ts
  exclude:
    - **/*.test.*`,
    );

    const config = loadConfig('/project');

    expect(config?.scope.include).toEqual(['src/**/*.ts']);
  });

  it('should parse config generated by init command', () => {
    vi.mocked(readFileSync).mockReturnValue(
      `# treck configuration
# Learn more: https://github.com/fredrivett/treck

output:
  # Where generated documentation will be stored
  dir: _treck

scope:
  # Files to include in documentation
  include:
    - src/**/*.{ts,tsx,js,jsx}

  # Files to exclude from documentation
  exclude:
    - **/*.test.ts
    - **/*.spec.ts
    - node_modules/**
    - dist/**
    - build/**
`,
    );

    const config = loadConfig('/project');

    expect(config).toEqual({
      outputDir: '_treck',
      scope: {
        include: ['src/**/*.{ts,tsx,js,jsx}'],
        exclude: ['**/*.test.ts', '**/*.spec.ts', 'node_modules/**', 'dist/**', 'build/**'],
      },
    });
  });
});
